### ISSUE TITLE
Polyfill UNSAFE_* aliases

### ISSUE THREAD

**Issue by motiz88** [reactjs/react-lifecycles-compat#2]
Per the [blog post](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path), React 16.3 will

> Introduce aliases for the unsafe lifecycles, `UNSAFE_componentWillMount`, `UNSAFE_componentWillReceiveProps`, and `UNSAFE_componentWillUpdate`.

Is there an intention to polyfill these aliases here?

**Comment by bvaughn** [comment]
No. 😄

The "UNSAFE_" lifecycle aliases were introduced for applications that were too large to be migrated to async-safe coding patterns. (Facebook has a lot of these!)

On the other hand, this polyfill was created to enable _shared libraries_ (e.g. `react-router`) to support older and newer versions of React. We want shared libraries to be async-safe (since applications that rely on them may want to use async rendering). So it doesn't make sense to polyfill the unsafe lifecycles.
