### ISSUE TITLE
IE 10 support

### ISSUE THREAD

**Issue by miketamis** [reactjs/react-lifecycles-compat#28]
When running our react project in IE10 I get this error in the console and component doesn't load

```
"Can only polyfill class components"
```

**Comment by bvaughn** [comment]
The error you reference is only thrown if the `Component` you polyfill doesn't have an `isReactComponent` property on its prototype. This property is set by React on `Component` (and `React.PureComponent`), and your component should inherit it so long as it extends one of those two classes.

Since you mention IE 10 specifically, it does not support JavaScript class syntax. This means that you'll need to use something like Babel to compile your code before running it.

If you are doing this and still seeing the error, we'll need more information bout how to reproduce the problem. (For example, you can provide a [Code Sandbox](https://codesandbox.io/s/new) that shows all of your code, or an example GitHub repo that could be checked out and run locally.

PS. Can you load this URL in IE 10 by chance?
https://build-bmxsryfowt.now.sh

**Comment by miketamis** [comment]
https://build-bmxsryfowt.now.sh isn't loading in ie 10, because you haven't polyfilled Set and Map.

https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by bvaughn** [comment]
I'm familiar with that requirement. 😄 The app I deployed to [build-bmxsryfowt.now.sh](https://build-bmxsryfowt.now.sh) used the polyfills mentioned on ReactJS.org specifically. I messed up though by putting them in `App.js` rather than `index.js` (after React has been initialized in other words). Try again:

https://build-billqnpauw.now.sh

**Comment by miketamis** [comment]
It works 😄 
Must be something we done in our project. I'll investigate more.

**Comment by bvaughn** [comment]
When you figure out the cause– let me know, if you think about it. It might be helpful in the future for someone else. :smile:
