### ISSUE TITLE
Is there intent to support componentDidCatch and getDerivedStateFromError?

### ISSUE THREAD

**Issue by BrendanFDMoore** [reactjs/react-lifecycles-compat#33]
Should we expect to be able to eventually use this to migrate to using Error Boundary implementations by leveraging the new error-related lifecycle methods?

Docs do not mention one way or the other.

**Comment by bvaughn** [comment]
Error boundaries (introduced in v16.0 with `componentDidCatch`) are not something that can be polyfilled for older versions of React. They're a totally new behavior and not something that could be simulated using pre-existing lifecycles.

I believe it would be possible to polyfill `getDerivedStateFromError` for v16.0.x-16.5.x using `componentDidCatch` but I would need to think about it more to be sure.

That being said, it is not as important to polyfill `getDerivedStateFromError` as it was for `getDerivedStateFromProps` and `getSnapshotBeforeUpdate`. [Those lifecycles came with deprecation warnings](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) so it was important that we provided library authors with some way of upgrading their components in order to support both older and newer versions of React without cluttering the console with dev warnings.

**Comment by bvaughn** [comment]
No problem 😄 It's a good question.

Dan pointed out that the `react-lifecycles-compat` package is primarily intended for library authors (so they can support multiple React versions downstream), and we don't expect it to be common for libraries to define their own error boundaries. (Error boundaries are lightweight and typically application-specific.)

So I think we can close this issue as a non-goal for now!
