### ISSUE TITLE
1.1.1 error __webpack_require___(...) is not a function

### ISSUE THREAD

**Issue by johntran** [reactjs/react-lifecycles-compat#7]
Hi there!

When using `react-relay` v.1.5.0, the following error is given.

<img width="1526" alt="screenshot 2018-04-02 14 11 20" src="https://user-images.githubusercontent.com/3813391/38216486-bc0c6280-367f-11e8-92e7-1830277609c7.png">

The error points to this line:

https://github.com/facebook/relay/blob/256b7a77e9f8b9d360282580c9a316c5f079ee13/packages/react-relay/modern/ReactRelayQueryRenderer.js#L313

It seems like the import line 19 no longer works.

`const polyfill = require('react-lifecycles-compat');`

When I install `react-lifecycles-compat` v.1.1.0 to project, then the error disappears. 

Thoughts?

**Comment by bvaughn** [comment]
Hm. This is unexpected. Can you share a repro?

**Comment by johntran** [comment]
@bvaughn 

So the problem isn't in the official react-relay build. The problem is in a forked build.

Context: If you want to use TypeScript in Relay Modern, you have to use a forked version of it. And the forked version of it is broken with the react-lifecycles-compat 1.1.1 update.

https://github.com/johntran/relay-examples

Repro steps:
1. Pull from `master`. `yarn`
2. `yarn update-schema`
3. `yarn build`
4. `yarn start`

This issue could be possibly fixed if I rebuild the fork. But the original Relay package was able to work without a fork to fix the webpack require issue.

Thoughts?

**Comment by bvaughn** [comment]
I believe I've made a mistake with this API. I should not have used a default export for the CJS package, because there is no direct ES module equivalent.

I think the fix here is to:
1. Publish 1.1.2 with no ES module
2. Release 2.0 with a named `polyfill` export (both CJS and ES) so they're compatible.

Related issues:
* webpack/webpack/issues/4742
* facebook/react/issues/11503

cc @Andarist

**Comment by bvaughn** [comment]
I wasn't aware. I wish we'd discussed it in the PR. (My fault.)

It's not realistic to assume that everyone is using Rollup. 😄 We can chat about this tomorrow. For now, I'm publishing 1.1.2 without the ES module.

**Comment by Andarist** [comment]
> It's not realistic to assume that everyone is using Rollup.

Sure thing, I just meant that rollup has emitted the same CJS shape as one that was previously written "by hand" - so I thought it shouldnt cause any issues

I think I know what happened here though 🙈It's happening because a CJS file requests module that has `"module"` entry point and bundler tries to translate it to CJS so the requesting file can consume it. And unfortunately, as you have pointed out, it can't reliably do that - it wraps the module and expose it to CJS file as an object with `.default` property.

Sorry for this one, totally forgot that this can happen.

@bvaughn are u opposed to releasing 2.0 soon-ish? That would fix this & provide benefits of the "module" entry.

**Comment by bvaughn** [comment]
No worries 😄I didn't consider that case either.

I'll get back to you about timing.

**Comment by bvaughn** [comment]
Release 1.1.1 has been deprecated (so it will log a warning if it's added) and 1.1.2 has been released without ES modules. That should be sufficient to close this issue.

I'll move the remainder of the work (discussion about breaking changes) to a new issue.
